version: '3.8'

services:
  trmnl-quote-plugin:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - QUOTES_FILE_PATH=/app/quotes.json
      - REFRESH_INTERVAL_MINUTES=30
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
